### PR TITLE
add delay before deletefolderrecursive

### PR DESCRIPTION
**Pull request by jairoxyz**
I found that an async 5 sec delay between closing the browser/session and calling deletefolderecursive seems to solve the problem with locked files on some OS such as Windows.

### CODE REVIEW

**Comment by NoahCardoza** [comment]
Actually, why don't we try awaiting `browser.close()`? If it's a matter of the files still being in use by the browser process? See if that fixes it since I don't have a Windows machine to test it on right now.

**Comment by jairoxyz** [comment]
OK, I will give it a try. Another explanation that came to my mind is that we have been using unlinkSync, which is blocking. The timeout function seems to add some async behavior to it, so maybe using unlink (async) will solve it, too. I'll do some more tests and let you know.

**Comment by jairoxyz** [comment]
No luck with await `browser.close()` nor with using an async version of the deletefolder function. Really stupid behavior on Windows and the only workaround so far is the async sleep for 5 secs as it this PR.

**Comment by NoahCardoza** [comment]
Pulled this into a local branch and merged it manually so I could make some slight changes. Btw, I'll be moving development to [CloudProxy](https://github.com/NoahCardoza/CloudProxy) so we can open issues on the repo that's actually getting the updates.

**Pull request closed without merging**
